[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ancient = "2euLYQyMsH2WYZ2DgVXfAUZMRmpG179v69M5RcBCuCGf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
